language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-26
    - ANDROID_ABI=armeabi-v7a -c 100M
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - $ANDROID_TARGET
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
after_success:
  - bash <(curl -s https://codecov.io/bash)