language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-26
    - ANDROID_ABI=armeabi-v7a -c 100M
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - $ANDROID_TARGET
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - curl -Ls -o codacy-coverage-reporter "$(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | contains("codacy-coverage-reporter-linux"))) | .[0].browser_download_url')"
  - chmod +x codacy-coverage-reporter
  - ./codacy-coverage-reporter report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)